# Generated by Django 5.2.4 on 2025-08-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='role',
            field=models.CharField(default='user', max_length=20),
            preserve_default=False,
        ),
    ]
