# Generated by Django 5.2.4 on 2025-08-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='aadhaar_file',
            field=models.FileField(blank=True, null=True, upload_to='aadhaar_uploads/'),
        ),
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.CharField(default='rahi', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
