# Generated by Django 5.2.4 on 2025-08-19 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_register_aadhaar_file_register_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='password',
        ),
        migrations.RemoveField(
            model_name='register',
            name='username',
        ),
        migrations.AddField(
            model_name='register',
            name='login',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.login'),
        ),
        migrations.AlterField(
            model_name='register',
            name='aadhaar_file',
            field=models.FileField(blank=True, null=True, upload_to='aadhaar_files/'),
        ),
        migrations.AlterField(
            model_name='register',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
