# Generated by Django 5.2.4 on 2025-08-22 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_register_password_remove_register_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Birthday', 'Birthday'), ('Marriage', 'Marriage'), ('Engagement', 'Engagement'), ('Festival', 'Festival'), ('Corporate', 'Corporate'), ('Other', 'Other')], max_length=50)),
                ('place_type', models.CharField(choices=[('Convention Center', 'Convention Center'), ('Hall', 'Hall'), ('Destination', 'Destination'), ('Home', 'Home'), ('Outdoor Ground', 'Outdoor Ground')], max_length=50)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.register')),
            ],
        ),
    ]
