# Generated by Django 5.2.4 on 2025-08-26 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_event_vacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
    ]
