# Generated by Django 5.2.4 on 2025-08-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_register_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
