# Generated by Django 5.2.4 on 2025-08-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_login_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='email',
        ),
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=20),
        ),
    ]
