# Generated by Django 5.2.4 on 2025-08-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_confirmation_decline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decline',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='decline',
            name='event',
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('employee', 'event')},
        ),
        migrations.DeleteModel(
            name='Confirmation',
        ),
        migrations.DeleteModel(
            name='Decline',
        ),
    ]
