# Generated by Django 5.2.4 on 2025-09-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_decline_employee_remove_decline_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Confirmed', 'Confirmed'), ('Declined', 'Declined'), ('Cant Attend', 'Cant Attend')], default='Applied', max_length=20),
        ),
    ]
