# Generated by Django 5.2.4 on 2025-09-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='vacancy',
            field=models.IntegerField(default=0),
        ),
    ]
