# Generated by Django 5.2.4 on 2025-09-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_event_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
