# Generated by Django 5.2.4 on 2025-09-12 09:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_event_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='applied_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
